print("       * ")
print("      ***")
print("     *****")
print("    *******")
print("   *********")
print("  ***********")
print()
print("using a new method")
print(" "*6, '*'*1)
print(" "*5, '*'*3)
print(" "*4, '*'*5)
print(" "*3, '*'*7)
print(" "*2, '*'*9)
print(" "*1, '*'*11)
